// Embeds assets/*.glb as base64 into js/assets-data.js, so the props also load from file:// and in the bundle.
//   node tools/pack-assets.mjs   (run after rebuilding the props in Blender: python tools/blender/build.py …)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets');
const files = readdirSync(dir).filter((f) => f.endsWith('.glb')).sort();
let total = 0;
const lines = files.map((f) => {
  const b64 = readFileSync(join(dir, f)).toString('base64'); total += b64.length;
  return `  ${basename(f, '.glb')}: '${b64}',`;
});
writeFileSync(join(root, 'js', 'assets-data.js'),
  `// Generated by tools/pack-assets.mjs from assets/*.glb (props modelled and baked in Blender: tools/blender/). Do not edit.\nexport const GLB = {\n${lines.join('\n')}\n};\n`);
console.log(`js/assets-data.js: ${files.length} models, ${(total / 1024).toFixed(0)} KB base64`);
